spring:
  application:
    name: beneficiary-services
  data:
    mongodb:
      uri: mongodb://${MONGO_DATABASE_USER}:${MONGO_DATABASE_PASSWORD}@mongodb/${MONGO_DATABASE_NAME}
  jpa: 
    hibernate: 
      ddl-auto: update
server:
  port: 8080
eureka: 
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
   endpoint:
      health:
        show-details: "ALWAYS"
      metrics :
        enabled : true
      prometheus : 
        enabled : true
   metrics :
      export : 
         prometheus : 
           enabled : true
           
   endpoints:
    web:
      exposure:
        include: "*"
        exclude: env,beans
